//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente.WsUsuario {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsUsuario.MiServicioSoap")]
    public interface MiServicioSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Listado();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listado", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListadoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListadoParametro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ListadoParametro(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListadoParametro", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListadoParametroAsync(string rut);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MiServicioSoapChannel : Cliente.WsUsuario.MiServicioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MiServicioSoapClient : System.ServiceModel.ClientBase<Cliente.WsUsuario.MiServicioSoap>, Cliente.WsUsuario.MiServicioSoap {
        
        public MiServicioSoapClient() {
        }
        
        public MiServicioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MiServicioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MiServicioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MiServicioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public System.Data.DataSet Listado() {
            return base.Channel.Listado();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListadoAsync() {
            return base.Channel.ListadoAsync();
        }
        
        public System.Data.DataSet ListadoParametro(string rut) {
            return base.Channel.ListadoParametro(rut);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListadoParametroAsync(string rut) {
            return base.Channel.ListadoParametroAsync(rut);
        }
    }
}
